#!/usr/bin/env bash
# Builds the reduction binary for multiple architectures
set -ueo pipefail

OUTPUT_DIR="build"
mkdir -p "$OUTPUT_DIR/linux-amd64" "$OUTPUT_DIR/linux-arm64"

# Build for amd64
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o "$OUTPUT_DIR/linux-amd64/reduction" ./cmd/reduction

# Build for arm64
GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o "$OUTPUT_DIR/linux-arm64/reduction" ./cmd/reduction

# build for local
go build -o "$OUTPUT_DIR/reduction" ./cmd/reduction
