#!/usr/bin/env bash
set -ue
shopt -s globstar

TOOLS_BIN="./bin"
PROTOCOL_PATH="${PROTOCOL_PATH:-../reduction-protocol}"

./bin/protoc/bin/protoc \
  -I ${PROTOCOL_PATH} \
  -I . \
  --plugin=protoc-gen-go=./bin/protoc-gen-go \
  --go_opt=paths=source_relative \
  --go_out=. \
  --plugin=protoc-gen-connect-go=./bin/protoc-gen-connect-go \
  --connect-go_opt=paths=source_relative \
  --connect-go_out=. \
  proto/**/*.proto connectors/**/*.proto
