#!/usr/bin/env bash
set -ue

TOOLS_DIR="./vendor"

## protoc installation

# Make temporary directory for downloads
TMP_DIR=$(mktemp -d)

# Determine platform based on environment
if [ "${GITHUB_ACTIONS:-}" = "true" ]; then
    PLATFORM="linux-x86_64"
else
    PLATFORM="osx-aarch_64"
fi

# Download and unzip file
PROTOC_VERSION="29.3"
PROTOC_RELEASE="https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-${PLATFORM}.zip"
curl --location $PROTOC_RELEASE --output ${TMP_DIR}/protoc.zip
mkdir -p ${TOOLS_DIR}/protoc
unzip -o ${TMP_DIR}/protoc.zip -d ${TOOLS_DIR}/protoc
chmod u+x ${TOOLS_DIR}/protoc/bin/protoc

# Remove temporary files
rm -rf ${TMP_DIR}

## Other go tools installation

# Loop through the packages and install each one
TOOLS=(
  "connectrpc.com/connect/cmd/protoc-gen-connect-go@v1.18.1"
  "google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.2"
)
for PKG in "${TOOLS[@]}"; do
  GOBIN=$(pwd)/${TOOLS_DIR} go install ${PKG}
done

# Check if globstar is available in the current Bash version
if ! shopt -s globstar; then
    echo "Error: globstar is not supported in this version of Bash."
    echo $(bash --version)
    exit 1
fi
