name: Test

on:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.0'

      # Setup tools before generating code
      - name: Setup Tools
        run: ./scripts/setup

      # Generate protobuf code - the modified gen script now handles the dependencies
      - name: Generate Code
        run: ./scripts/gen

      # Now install all dependencies after generated code exists
      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: go test ./... -v
